---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: wnc
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: wnc-app
    template:
      metadata:
        labels:
          name: wnc-app
      spec:
        containers:
          - name: application
            image: 20191612557/wnc:v2.6
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 5000