---
    apiVersion: v1
    kind: Service
    metadata:
      name: frontend-wnc-employee-admin-service
    spec:
      type: LoadBalancer
      ports:
      - name: http
        port: 80
        targetPort: 80
      selector:
          name: frontend-wnc-employee-admin-app